###############################################################################################################################
#                                                              #                                                              #
#          _______ _    _ ______   _____ _____ _______         #          _______ _    _ ______   _____ _____ _______         #
#        |__   __| |  | |  ____| |  __ \_   _|__   __|         #        |__   __| |  | |  ____| |  __ \_   _|__   __|         #
#           | |  | |__| | |__    | |__) || |    | |            #           | |  | |__| | |__    | |__) || |    | |            #
#           | |  |  __  |  __|   |  ___/ | |    | |            #           | |  |  __  |  __|   |  ___/ | |    | |            #
#           | |  | |  | | |____  | |    _| |_   | |            #           | |  | |  | | |____  | |    _| |_   | |            #
#           |_|  |_|  |_|______| |_|   |_____|  |_|            #           |_|  |_|  |_|______| |_|   |_____|  |_|            #
#                                                              #                                                              #
###############################################################################################################################





#########################################################################################################################
#             _____      _   _   _                          #             _____      _   _   _                          #
#            / ____|    | | | | (_)                         #            / ____|    | | | | (_)                         #
#           | (___   ___| |_| |_ _ _ __   __ _ ___          #           | (___   ___| |_| |_ _ _ __   __ _ ___          #
#            \___ \ / _ \ __| __| | '_ \ / _` / __|         #            \___ \ / _ \ __| __| | '_ \ / _` / __|         #
#            ____) |  __/ |_| |_| | | | | (_| \__ \         #            ____) |  __/ |_| |_| | | | | (_| \__ \         #
#           |_____/ \___|\__|\__|_|_| |_|\__, |___/         #           |_____/ \___|\__|\__|_|_| |_|\__, |___/         #
#                                         __/ |             #                                         __/ |             #
#                                        |___/              #                                        |___/              #
#########################################################################################################################


AutoUpdater: true       # true - enabled, false - disabled;
Language: 2             # Allowed languages: Russian - 1, English - 2.

MySQL:
  username: "Admin"
  password: "password"
  port: "3306"
  host: "localhost"
  dbname: "thepit"

RU:
  scoreboard:
    1: "§e"
    2: "§c➥ §fИнформация"
    3: "Уровень: §8[<level>§8]"
    4: "<indicator>"
    5: "Престиж: §c<prestige>"
    6: "Золота: §c<coins>"
    7: "Опыт: §c<xp>"
    8: "Опыта надо: §c<xpneed>"
    9: "§c"
    10: "§c➥ §fСервер"
    11: "Онлайн: §c<players>"
    12: "§a"
    13: "§cwww.yoursite.com"

    maxlevel: "Опыта надо: §cМаксимум"

Indicator:
  Symbol: "|"
  TotalBars: 30
  CompletedColor: "&c"
  NotCompletedColor: "&7"

EN:
  scoreboard:
    1: "§e"
    2: "§c➥ §fInformation"
    3: "Level: §8[<level>§8]"
    4: "<indicator>"
    5: "Prestige: §c<prestige>"
    6: "Gold: §c<coins>"
    7: "Exp: §c<xp>"
    8: "Exp needed: §c<xpneed>"
    9: "§c"
    10: "§c➥ §fServer"
    11: "Online: §c<players>"
    12: "§a"
    13: "§cwww.yoursite.com"

    maxlevel: "Exp needed: §cMaximum"

ChatFormatting:
  enabled: true
  HavePrestige: "§c<prestige> §8[§c<level>§8] §7<player>§8: §f<message>"
  NoPrestige: "§8[§c<level>§8] §7<player>§8: §f<message>"